# Generated by Django 3.1.7 on 2021-05-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210512_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereviews',
            options={'verbose_name_plural': 'Site Reviews'},
        ),
    ]
