# Generated by Django 3.1.7 on 2021-05-12 23:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20210512_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereviews',
            name='user',
            field=models.OneToOneField(null=True, on_delete=models.SET('Anonymous User'), to=settings.AUTH_USER_MODEL),
        ),
    ]
