# Generated by Django 3.1.7 on 2021-05-13 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20210512_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereviews',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('Anonymous User'), to='auth.user'),
        ),
    ]
