# Generated by Django 3.1.7 on 2021-05-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('home', '0009_auto_20210513_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Anonymous User'), to='profiles.userprofile'),
        ),
    ]
