# Generated by Django 3.1.7 on 2021-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210514_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereviews',
            options={'ordering': ('date',), 'verbose_name_plural': 'Site Reviews'},
        ),
    ]
